apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-test-pvc
  namespace: tanzuns1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 190Gi
  storageClassName: tanzu
  volumeMode: Filesystem
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm-selector: minio-test-vm
  name: minio-test-vm
  namespace: tanzuns1
spec:
  imageName: centos-stream-8-vmservice-v1alpha1-1619529007339
  className: best-effort-medium
  powerState: poweredOn
  storageClass: tanzu
  networkInterfaces:
  - networkType: nsx-t
    networkName: ""
  volumes:
  - name: minio-test-vol
    persistentVolumeClaim:
      claimName: minio-test-pvc
  readinessProbe:
    tcpSocket:
      port: 22
  vmMetadata:
    configMapName: minio-test-cloudinit
    transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-test-cloudinit
  namespace: tanzuns1
data:
  user-data: I2Nsb3VkLWNvbmZpZwpjaHBhc3N3ZDoKICAgIGxpc3Q6IHwKICAgICAgY2VudG9zOlZNd2FyZTEhCiAgICBleHBpcmU6IGZhbHNlCmdyb3VwczoKICAtIGRvY2tlcgp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IGNlbnRvcwogICAgc3NoLWF1dGhvcml6ZWQta2V5czoKICAgICAgLSBzc2gtcnNhIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQ0FRRFN3eUYrNktIT0NqK21uSGdmd0xhQ1hnWmNKcng2c2F0VUhOc3Vhd1llTkhDZ3FjVkJnTFhtcnZ0VFF1VWNMakJUZzNiM012bDhzVmpNNmdXQnJrdUpkQ0FmRnZHcVR1N2ppQ3BQdXQ4cEppb01xdWFycnFtOGxNQlFMRlRLQlAva3pHZlBuZjJ1NHB2eHE3NG9nWlNJSlRycXZyc29ab29yNDNVM05zOHJTSU1QODM1S09ZRFlTWXhKcUNxUE9hb0xwblBJOHEwLzRTaGd4VFNtcjB3ZytEbXR6YjFzVzllNDJhb1JKd2UyS21yTzdVb3VLbzd1eEl1VVNtSng5VnNVOEYrdUJMRFVNSUU1ZlNnRlNxYW5iRmNnWXQrdHBIdGwvWHZVTDF2NjdwQlhvanFNU29laFRjZ0NBOUNWUDlHcHVtamJ4UjlKUTB3d0hFTGVhTis2UkM3M2g3REsrSldZZlUrRk9qL3hmRkRyaGRDekpHOHdlaEhTR0RIVU5OQ0JxakVJK296TG9UQTFiTmxBcVdQVUk1cmxycWI3dkpLOXJjVEhyblFmNm5sanIvUmZTOFk5S3BMQzNpcUxPTzF3S28wV3dQYVlkUkxnSUVCQ0xqbi84SW14M2d2MXNoN3p0SFRZYmk2VElhUUlTNnFUWFE0ZDBzcnR3a2xkUUdpdko5TnJ3dnN5dHRvZjlsa1RwdFlKVWVOVTIyMzF6QnBIY1F4Tm9DYm1QeWkweWZmb0FKcS9BSHRJTEtLQ3YrcU03RTh1NnRaTHZLOFI0UWd3cHUxMWlMclpOZDNQQVRTTEwzZjRZYld2T256MkYxZVNVSVBOTjBLMjRDZkxzWjFWdkhFaFBnbCtHMkdLK1gxV1VwQnVDc0Nsdm1KMFd0MVo4S0tRL3IzUjd3PT0gZ29ya2Vtb0B2bXdhcmUuY29tCiAgICBzdWRvOiBBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMCiAgICBncm91cHM6IHN1ZG8sIGRvY2tlcgogICAgc2hlbGw6IC9iaW4vYmFzaApuZXR3b3JrOgogIHZlcnNpb246IDIKICBldGhlcm5ldHM6CiAgICAgIGVuczE5MjoKICAgICAgICAgIGRoY3A0OiB0cnVlCnBhY2thZ2VfdXBkYXRlOiB0cnVlCnl1bV9yZXBvczoKICBkb2NrZXItY2Utc3RhYmxlOgogICAgbmFtZTogRG9ja2VyIENFIFN0YWJsZSAtICRiYXNlYXJjaAogICAgYmFzZXVybDogaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L2NlbnRvcy8kcmVsZWFzZXZlci8kYmFzZWFyY2gvc3RhYmxlCiAgICBlbmFibGVkOiB0cnVlCiAgICBncGdjaGVjazogdHJ1ZQogICAgZ3Bna2V5OiBodHRwczovL2Rvd25sb2FkLmRvY2tlci5jb20vbGludXgvY2VudG9zL2dwZwptb3VudHM6CiAgLSBbIC9kZXYvc2RiMSwgL2RhdGEsICJ4ZnMiLCAiZGVmYXVsdHMiLCAiMCIsICIyIiBdCnBhY2thZ2VzOgogIC0gbmV0LXRvb2xzCiAgLSB3Z2V0CndyaXRlX2ZpbGVzOgogIC0gcGF0aDogL29wdC9taW5pby9taW5pby5jb25mCiAgICBjb250ZW50OiB8CiAgICAgIE1JTklPX1ZPTFVNRVM9L2RhdGEvbWluaW8vZGF0YQogICAgICBNSU5JT19ST09UX1VTRVI9bWluaW8KICAgICAgTUlOSU9fUk9PVF9QQVNTV09SRD1taW5pbzEyMwogICAgb3duZXI6ICdyb290OnJvb3QnCiAgICBwZXJtaXNzaW9uczogJzA0NDQnCiAgLSBwYXRoOiAvZXRjL3N5c3RlbWQvc3lzdGVtL21pbmlvLnNlcnZpY2UKICAgIGNvbnRlbnQ6IHwKICAgICAgW1VuaXRdCiAgICAgIERlc2NyaXB0aW9uPU1pbmlvCiAgICAgIERvY3VtZW50YXRpb249aHR0cHM6Ly9kb2NzLm1pbmlvLmlvCiAgICAgIFdhbnRzPW5ldHdvcmstb25saW5lLnRhcmdldAogICAgICBBZnRlcj1uZXR3b3JrLW9ubGluZS50YXJnZXQKICAgICAgQXNzZXJ0RmlsZUlzRXhlY3V0YWJsZT0vb3B0L21pbmlvL2Jpbi9taW5pbwogICAgICAKICAgICAgW1NlcnZpY2VdCiAgICAgIFdvcmtpbmdEaXJlY3Rvcnk9L29wdC9taW5pbwogICAgICAKICAgICAgVXNlcj1yb290CiAgICAgIEdyb3VwPXdoZWVsCiAgICAgIAogICAgICBQZXJtaXNzaW9uc1N0YXJ0T25seT10cnVlCiAgICAgIAogICAgICBFbnZpcm9ubWVudEZpbGU9LS9vcHQvbWluaW8vbWluaW8uY29uZgogICAgICBFeGVjU3RhcnRQcmU9L2Jpbi9iYXNoIC1jICJbIC1uIFwiJHtNSU5JT19WT0xVTUVTfVwiIF0gfHwgZWNobyBcIlZhcmlhYmxlIE1JTklPX1ZPTFVNRVMgbm90IHNldCBpbiAvb3B0L21pbmlvL21pbmlvLmNvbmZcIiIKICAgICAgCiAgICAgIEV4ZWNTdGFydD0vb3B0L21pbmlvL2Jpbi9taW5pbyBzZXJ2ZXIgJE1JTklPX09QVFMgLS1hZGRyZXNzIDAuMC4wLjA6OTAwMCAtLWNvbnNvbGUtYWRkcmVzcyAwLjAuMC4wOjkwMDEgJE1JTklPX1ZPTFVNRVMKICAgICAgCiAgICAgIFN0YW5kYXJkT3V0cHV0PWpvdXJuYWwKICAgICAgU3RhbmRhcmRFcnJvcj1pbmhlcml0CiAgICAgIAogICAgICAjIFNwZWNpZmllcyB0aGUgbWF4aW11bSBmaWxlIGRlc2NyaXB0b3IgbnVtYmVyIHRoYXQgY2FuIGJlIG9wZW5lZCBieSB0aGlzIHByb2Nlc3MKICAgICAgTGltaXROT0ZJTEU9NjU1MzYKICAgICAgCiAgICAgICMgRGlzYWJsZSB0aW1lb3V0IGxvZ2ljIGFuZCB3YWl0IHVudGlsIHByb2Nlc3MgaXMgc3RvcHBlZAogICAgICBUaW1lb3V0U3RvcFNlYz0wCiAgICAgIAogICAgICAjIFNJR1RFUk0gc2lnbmFsIGlzIHVzZWQgdG8gc3RvcCBNaW5pbwogICAgICBLaWxsU2lnbmFsPVNJR1RFUk0KICAgICAgCiAgICAgIFNlbmRTSUdLSUxMPW5vCiAgICAgIAogICAgICBTdWNjZXNzRXhpdFN0YXR1cz0wCiAgICAgIAogICAgICBbSW5zdGFsbF0KICAgICAgV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQKICAgIG93bmVyOiByb290OnJvb3QKICAgIHBlcm1pc3Npb25zOiAnMDY0NCcKcnVuY21kOgogIC0gcGFydGVkIC9kZXYvc2RiIG1rbGFiZWwgZ3B0CiAgLSBwYXJ0ZWQgL2Rldi9zZGIgbWtwYXJ0IHByaW1hcnkgeGZzIDFNQiAxOTQ1NjBNQgogIC0gL3NiaW4vbWtmcy54ZnMgL2Rldi9zZGIxCiAgLSBta2RpciAtcCAvZGF0YQogIC0gbW91bnQgLXQgeGZzIC0tcncgL2Rldi9zZGIxIC9kYXRhCiAgLSBta2RpciAtcCAvb3B0L21pbmlvL2JpbgogIC0gbWtkaXIgLXAgL2RhdGEvbWluaW8vZGF0YQogIC0gd2dldCAtcSBodHRwczovL2RsLm1pbmlvLmlvL3NlcnZlci9taW5pby9yZWxlYXNlL2xpbnV4LWFtZDY0L21pbmlvIC1PIC9vcHQvbWluaW8vYmluL21pbmlvCiAgLSBjaG1vZCAreCAvb3B0L21pbmlvL2Jpbi9taW5pbwogIC0gc3lzdGVtY3RsIGRhZW1vbi1yZWxvYWQKICAtIHN5c3RlbWN0bCBlbmFibGUgbWluaW8KICAtIHN5c3RlbWN0bCBzdGFydCBtaW5pbwogIC0gc3lzdGVtY3RsIHN0b3AgZmlyZXdhbGxkCiAgLSBzeXN0ZW1jdGwgZGlzYWJsZSBmaXJld2FsbGQKCg==
  hostname: minio-test-vm
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: minio-test-svc
  namespace: tanzuns1
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: secure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    vm-selector: minio-test-vm
  type: LoadBalancer
