apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: to-test-pvc
  namespace: tanzuns1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 190Gi
  storageClassName: tanzu
  volumeMode: Filesystem
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm-selector: to-test-vm
  name: to-test-vm
  namespace: tanzuns1
spec:
  imageName: centos-stream-8-vmservice-v1alpha1-1619529007339
  className: best-effort-medium
  powerState: poweredOn
  storageClass: tanzu
  networkInterfaces:
  - networkType: nsx-t
    networkName: ""
  volumes:
  - name: to-test-vol
    persistentVolumeClaim:
      claimName: to-test-pvc
  readinessProbe:
    tcpSocket:
      port: 22
  vmMetadata:
    configMapName: to-test-cloudinit
    transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: to-test-cloudinit
  namespace: tanzuns1
data:
  user-data: I2Nsb3VkLWNvbmZpZwpjaHBhc3N3ZDoKICAgIGxpc3Q6IHwKICAgICAgY2VudG9zOlZNd2FyZTEhCiAgICBleHBpcmU6IGZhbHNlCmdyb3VwczoKICAtIGRvY2tlcgp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IGNlbnRvcwogICAgc3NoLWF1dGhvcml6ZWQta2V5czoKICAgICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUURQNys3NzlpdW1DeHJlTjYxUEtjb3RjNk90MmpRMHViTlRkek5QRFRSNGpQZUJabmhxWDBwc2s0SmpxSlJsNUdEZEQ3ZFByLzNDZHdXeElPU00xZWg3ckRmZGdCZXh5dW1xYWVyV0haYlF4cksyQXpxWDBTNVRWSWtyZEJmWU9hOEI0UkdMYXEzejY2OE5YeGRIVFNyWHozUFdaUWpzSDdobFNROWRkZU14Nlc3OVB6Y3VucEtJbDRwV1pXNnJFNFlhbHdWVjlPbDZvVGRnTDZEaVAzdG53alpiK3AwNEhZelFuQVVKUndqS25QUnI0QWVZY1hYTWY4Z2NWSmZkYUlaTEFhcC92Vm11LzNUazBDVWh3VDYvNkNtRjk3K1QrbysyOW0yd3dFbUt3Nml1WmtEVkpIeGVSdFp1WEI2UHVmVVpWU2ZQT0V5UTJVZ2FuemdsNU8waWtFTmx1cEI0bUU3ellEc2V1TVlWVEtDY04yc1JMMWUraVFvb2JZRm4zbTVLNTFHM292dkMyREVQQ044dlpwNm11ZHhRTktLSW94RG1BN25aQTlvbisxY2F0aWJvMXA2VFhDL2t1dFpaejdVVGVqZlhtWldWWlVadGVmSit6NDZUUFM3aXhxaDJOQVZXbXozcWs4aS9la0Q2bGVlWEhzKzk1QmYrOXNaSmJ1Yz0gZ29ya2VtQGdvcmtlbW8tYTAxLnZtd2FyZS5jb20KICAgIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICAgIGdyb3Vwczogc3VkbywgZG9ja2VyCiAgICBzaGVsbDogL2Jpbi9iYXNoCm5ldHdvcms6CiAgdmVyc2lvbjogMgogIGV0aGVybmV0czoKICAgICAgZW5zMTkyOgogICAgICAgICAgZGhjcDQ6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKeXVtX3JlcG9zOgogIGRvY2tlci1jZS1zdGFibGU6CiAgICBuYW1lOiBEb2NrZXIgQ0UgU3RhYmxlIC0gJGJhc2VhcmNoCiAgICBiYXNldXJsOiBodHRwczovL2Rvd25sb2FkLmRvY2tlci5jb20vbGludXgvY2VudG9zLyRyZWxlYXNldmVyLyRiYXNlYXJjaC9zdGFibGUKICAgIGVuYWJsZWQ6IHRydWUKICAgIGdwZ2NoZWNrOiB0cnVlCiAgICBncGdrZXk6IGh0dHBzOi8vZG93bmxvYWQuZG9ja2VyLmNvbS9saW51eC9jZW50b3MvZ3BnCm1vdW50czoKICAtIFsgL2Rldi9zZGIxLCAvZGF0YSwgInhmcyIsICJkZWZhdWx0cyIsICIwIiwgIjIiIF0KcGFja2FnZXM6CiAgLSBkb2NrZXItY2UKICAtIGRvY2tlci1jZS1jbGkKICAtIGNvbnRhaW5lcmQuaW8KICAtIG5ldC10b29scwogIC0gd2dldApydW5jbWQ6CiAgLSBwYXJ0ZWQgL2Rldi9zZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAvZGV2L3NkYiBta3BhcnQgcHJpbWFyeSB4ZnMgMU1CIDE5NDU2ME1CCiAgLSAvc2Jpbi9ta2ZzLnhmcyAvZGV2L3NkYjEKICAtIG1rZGlyIC1wIC9kYXRhCiAgLSBtb3VudCAtdCB4ZnMgLS1ydyAvZGV2L3NkYjEgL2RhdGEKICAtIGRvY2tlciBydW4gLWQgLWUgV0FWRUZST05UX1VSTD1odHRwczovL3Ztd2FyZS53YXZlZnJvbnQuY29tL2FwaS8gLWUgV0FWRUZST05UX1RPS0VOPTg1ZjQ0MmNhLWQ4YWMtNDJmNC1iMmFlLTVlY2ZjYmNlMDNhYyAtZSAtcCAyODc4OjI4Nzggd2F2ZWZyb250aHEvcHJveHk6bGF0ZXN0CiAgLSBzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZAogIC0gc3lzdGVtY3RsIHN0b3AgZmlyZXdhbGxkCiAgLSBzeXN0ZW1jdGwgZGlzYWJsZSBmaXJld2FsbGQKCg==
  hostname: to-test-vm
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: to-test-svc
  namespace: tanzuns1
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: wf-proxy
    port: 2378
    protocol: TCP
    targetPort: 2378
  selector:
    vm-selector: to-test-vm
  type: LoadBalancer
